language: ruby

env:
  global:
    secure: "xKcz5Vv/p/8vcpsdh7/hUoYzcuAfXQEE81GtIR4ZcEt58oRMl2FQvBAWdY8cyfRoBJCFD3/kgcLkgxDnAS+xNIbKvaGtQEvvyrouXKx1qw44tuX072etH2iti7YJ+Vs/ctnn3PXBY9+Ul/LfKUCZrsXPaqe3jOHVeNDUuorXtM/Cw5Cnwo0mPgCj80+HxS5eLzgn3DjAZSW221P17VCkPql9/5ODfkZT4WgK9woqfljkOXWNLgnI1/MR0bMkgBFFjGBsXuctb6zYsKAVius2DuD4bihgl9B2ZTS1BRsKZf1NEjUsvSAyUaomeDCzNQyMn3bmGzQMUUBnbfRCD++tcaeaiNsYu86UvS1Y3wY/UcNKwbFF7FNcluDWbTox1Q+rrzgG7kshJtqbnHM0evleLa6v1zP9B3F7DpIoglTWEcfAm4cswUeKG+289aLn1P6GYMjGlByPnoOea7runiu+wSn8n1Qdy8opzHuYP4FRXgjYpDXPBhKedjvnQ1vgWHxvLLieh64QiYXKl0Kwhtb8XMNgSZ1knbUg9Zh3eADkzkC4gLWNAWNyZv8Quxjz8Q9j2WMfVj1NU8wvd2H3or6bKpKfifp9LykDGqK6SXESsqFhoq2qTalJ6a0lnAwkEmkDGp63d2L+Sqy5z13pUbEa2ZRQ3NdZ4tIDxiTiTysNlqg="

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master

script: bundle exec jekyll build

sudo: false
