language: ruby
# rvm:
# - 2.3.3

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: _site
  on:
    branch: master

script: bundle exec jekyll build

# sudo: false
