title: Elementory

timezone: Europe/Copenhagen

exclude:
- README.md
- LICENSE.txt
- Gemfile*

permalink: /:path/


defaults:
-
  scope:
    path: "*/p"
    scope: pages
  values:
    layout: post

-
  scope:
    path: oliver
  values:
    author:
      name: Oliver
      image: /assets/images/oliver.jpg
      tags:
      -
        url: /tags/taga
        name: Tag A
      -
        url: /tagb
        name: And tag B
      links:
      -
        name: Email
        url: mailto:oliversolow@gmail.com
        image: /assets/images/lettericon.png

-
  scope:
    path: peter
  values:
    author:
      name: Peter
      image: /assets/images/peter.jpg
      tags:
      -
        url: /petertag
        name: Tag

-
  scope:
    path: thor
  values:
    layout: post
    author:
      name: Thor
      image: /assets/images/thor.png
      tags:
      -
        url: /tagc
        name: Tag C
      links:
      -
        name: Email
        url: mailto:thor.ag.winther@gmail.com
        image: /assets/images/lettericon.png
      -
        name: Instragram
        url: http://www.instagram.com/thor.ag.winther/
        image: /assets/images/ig_logo.png
