title: Elementory's github.io page
baseurl: ""

timezone: Europe/Copenhagen

stylus:
  compress: false
  path: css

exclude:
- README.md
- LICENSE.txt
- Gemfile*
- .travis.yml
- vendor

include:
- .gitignore

permalink: /:slug/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
