title: Elementory

timezone: Europe/Copenhagen

exclude:
- README.md
- LICENSE.txt
- Gemfile*

permalink: /:slug/


collections:
  peter:
    output: true
    permalink: /:collection/:path
  oliver:
    output: true
    permalink: /:collection/:path
  thor:
    output: true
    permalink: /:collection/:path


defaults:
-
  scope:
    path: _oliver/p
    type: oliver
  values:
    layout: post
-
  scope:
    path: _peter/p
    type: peter
  values:
    layout: post
-
  scope:
    path: _thor/p
    type: thor
  values:
    layout: post
